# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in=
# http=//doc.scrapy.org/en/latest/topics/items.html

import scrapy


class DmOrderItem(scrapy.Item):

    # 表的结构:
    ord_id = scrapy.Field()
    ord_install_id = scrapy.Field()
    ord_merc_cost = scrapy.Field()
    ord_status = scrapy.Field()
    ord_is_back = scrapy.Field()
    ord_merc_id = scrapy.Field()
    ord_mast_id = scrapy.Field()
    ord_cust_name = scrapy.Field()
    ord_cust_sex = scrapy.Field()
    ord_cust_tel = scrapy.Field()
    ord_cust_addr = scrapy.Field()
    ord_province = scrapy.Field()
    ord_city = scrapy.Field()
    ord_district = scrapy.Field()
    ord_remark = scrapy.Field()
    ord_num = scrapy.Field()
    ord_weixin_num = scrapy.Field()
    ord_cust_told = scrapy.Field()
    ord_mast_cost = scrapy.Field()
    ord_cust_lat = scrapy.Field()
    ord_cust_lng = scrapy.Field()
    ord_purchase_unit = scrapy.Field()
    ord_purchase_unit_id = scrapy.Field()
    ord_type = scrapy.Field()
    ord_partner_id = scrapy.Field()
    ord_is_hide = scrapy.Field()


class AuxFactoryItem(scrapy.Item):
    # 工单详情item
    # define the fields for your item here like=
    factory_num  = scrapy.Field()
    aux_orderno  = scrapy.Field()
    platform_id  = scrapy.Field()
    accepted_at  = scrapy.Field()
    status  = scrapy.Field()


class ShiFuItem(scrapy.Item):
    name  = scrapy.Field()
    aux_num  = scrapy.Field()
    phone  = scrapy.Field()
    num  = scrapy.Field()


class MeidiDetailItem(scrapy.Item):
    APPOINT_TIME = scrapy.Field()
    UNIT_LEVEL = scrapy.Field()
    CUSTOMER_LEVEL = scrapy.Field()
    CUSTOMER_NAME = scrapy.Field()
    ACCOUNT_STATEMENT_TIME_ = scrapy.Field()
    UNIT_NAME = scrapy.Field()
    COMPLAINT_LEVEL = scrapy.Field()
    INTF_ORDER_CODE = scrapy.Field()
    DISPATCH_ORDER_TIME = scrapy.Field()
    RECEIVE_ORDER_TIME_ = scrapy.Field()
    BRAND_NAME = scrapy.Field()
    PURCHASING_CHANNELS_ = scrapy.Field()
    COMPLAINT_LEVEL_ = scrapy.Field()
    SERVICE_SUB_TYPE_CODE = scrapy.Field()
    FEEDBACK_TIME_ = scrapy.Field()
    PURCHASE_DATE = scrapy.Field()
    TMP_ROW_NO = scrapy.Field()
    COMPLAINT_FLAG = scrapy.Field()
    PROD_NAME = scrapy.Field()
    SERVICE_AREA_NAME = scrapy.Field()
    CONTACT_TIME_ = scrapy.Field()
    IMPLEMENT_SUB_TYPE_CODE_ = scrapy.Field()
    BRANCH_NAME = scrapy.Field()
    IMPLEMENT_SUB_TYPE_NAME = scrapy.Field()
    DISPATCH_ORDER_TIME_ = scrapy.Field()
    SERVICE_ORDER_ID = scrapy.Field()
    PURCHASE_DATE_ = scrapy.Field()
    CONTACT_TIME = scrapy.Field()
    CUSTOMER_TEL1 = scrapy.Field()
    SERVICE_AREA_CODE = scrapy.Field()
    SERVICE_CUSTOMER_NAME = scrapy.Field()
    COMPLAINT_FLAG_ = scrapy.Field()
    CONTACT_ORDER_SERV_TYPE_NAME = scrapy.Field()
    BRANCH_CODE = scrapy.Field()
    UNIT_CODE = scrapy.Field()
    CUSTOMER_AREA_CODE = scrapy.Field()
    IS_INPUT_ARCHIVES = scrapy.Field()
    URGENT_LEVEL = scrapy.Field()
    SERVICE_ORDER_NO = scrapy.Field()
    INFORMATION_FOLLOW_ = scrapy.Field()
    E_FEEDBACK_TIME_ = scrapy.Field()
    SERVICE_SUB_TYPE_NAME = scrapy.Field()
    FINISH_TIME = scrapy.Field()
    SERVICE_METHOD_CODE = scrapy.Field()
    AREA_NUM = scrapy.Field()
    CONTACT_ORDER_SER_ITEM2_NAME = scrapy.Field()
    SERVICE_DESC = scrapy.Field()
    ORDER_ORIGIN_ = scrapy.Field()
    CHANGE_APPOINT_TIME_ = scrapy.Field()
    SERVICE_TYPE_CODE = scrapy.Field()
    RECEIVE_ORDER_PERSON = scrapy.Field()
    CONTAIN_EJFWS = scrapy.Field()
    PROD_NUM = scrapy.Field()
    PUB_CREATE_DATE = scrapy.Field()
    RECEIVE_ORDER_TIME = scrapy.Field()
    URGENT_LEVEL_ = scrapy.Field()
    PRODUCT_USE = scrapy.Field()
    CONTAIN_EJFWS_ = scrapy.Field()
    PROD_CODE = scrapy.Field()
    SERVICE_CUSTOMER_DEMAND_ID = scrapy.Field()
    IMPLEMENT_SUB_TYPE_CODE = scrapy.Field()
    SERVICE_CUSTOMER_TEL1 = scrapy.Field()
    CHANGE_APPOINT_TIME = scrapy.Field()
    SERVICE_CUSTOMER_ADDRESS = scrapy.Field()
    CUSTOMER_LEVEL_ = scrapy.Field()
    INFORMATION_FOLLOW = scrapy.Field()
    PRODUCT_USE_ = scrapy.Field()
    FEEDBACK_TIME = scrapy.Field()
    SERVICE_TYPE_CODE_ = scrapy.Field()
    PUB_CREATE_PERSON = scrapy.Field()
    FINISH_TIME_ = scrapy.Field()
    SERVICE_METHOD_NAME = scrapy.Field()
    PURCHASING_CHANNELS = scrapy.Field()
    ACCOUNT_STATEMENT_TIME = scrapy.Field()
    E_FEEDBACK_TIME = scrapy.Field()
    SERVICE_ORDER_STATUS_ = scrapy.Field()
    ORDER_ORIGIN = scrapy.Field()
    SERVICE_ORDER_STATUS = scrapy.Field()


class MeidiEngineerItem(scrapy.Item):
    serviceOrderNo = scrapy.Field()
    serviceUserDemandIds = scrapy.Field()
    engineerId = scrapy.Field()
    engineerCode = scrapy.Field()
    engineerLevel = scrapy.Field()
    engineerTel = scrapy.Field()
    engineerName = scrapy.Field()
    workNo = scrapy.Field()
    unitCode = scrapy.Field()
    reassignmentReason = scrapy.Field()
    operator = scrapy.Field()
    operateTime = scrapy.Field()
    page = scrapy.Field()
    pageIndex = scrapy.Field()
    pageSize = scrapy.Field()
    rows = scrapy.Field()
    count = scrapy.Field()
    mapInfo = scrapy.Field()

